- hosts: all
  name: Install chocolatey.

  tasks:
    - name: "Check for existing chocolatey install."
      win_stat:
        path: "{{ chocolatey_path }}/choco.exe"
        register: chocolatey_exe

    - name: "Install Chocolatey."
      raw: "iex ((New-Object System.Net.WebClient).DownloadString('{{ chocolatey_installer }}'))"
      when:
        - chocolatey_exe.stat.exists is defined
        - not chocolatey_exe.stat.exists
